/**
 * AUTO-GENERATED by scripts/generate-currencies.mjs — DO NOT EDIT BY HAND.
 *
 * Source: ISO 4217 (currency-codes), currency-symbol-map, i18n-iso-countries.
 * Regenerate with: node scripts/generate-currencies.mjs
 *
 * Embedded ISO 4217 currency dataset plus a small curated crypto set.
 */

import type { Currency } from '../types.js';

export const CURRENCIES: readonly Currency[] = [
  {
    "code": "AED",
    "numeric": "784",
    "name": "UAE Dirham",
    "symbol": "د.إ",
    "minorUnits": 2,
    "countries": [
      "AE"
    ],
    "aliases": [
      "dirham",
      "uae dirham",
      "emirati dirham"
    ],
    "crypto": false
  },
  {
    "code": "AFN",
    "numeric": "971",
    "name": "Afghani",
    "symbol": "؋",
    "minorUnits": 2,
    "countries": [
      "AF"
    ],
    "aliases": [
      "afghani",
      "afghan afghani"
    ],
    "crypto": false
  },
  {
    "code": "ALL",
    "numeric": "008",
    "name": "Lek",
    "symbol": "L",
    "minorUnits": 2,
    "countries": [
      "AL"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "AMD",
    "numeric": "051",
    "name": "Armenian Dram",
    "symbol": "֏",
    "minorUnits": 2,
    "countries": [
      "AM"
    ],
    "aliases": [
      "dram",
      "armenian dram"
    ],
    "crypto": false
  },
  {
    "code": "ANG",
    "numeric": "532",
    "name": "Netherlands Antillean Guilder",
    "symbol": "ƒ",
    "minorUnits": 2,
    "countries": [
      "CW",
      "SX"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "AOA",
    "numeric": "973",
    "name": "Kwanza",
    "symbol": "Kz",
    "minorUnits": 2,
    "countries": [
      "AO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "ARS",
    "numeric": "032",
    "name": "Argentine Peso",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "AR"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "AUD",
    "numeric": "036",
    "name": "Australian Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "AU",
      "CX",
      "CC",
      "HM",
      "KI",
      "NR",
      "NF",
      "TV"
    ],
    "aliases": [
      "australian dollar",
      "aussie dollar"
    ],
    "crypto": false
  },
  {
    "code": "AWG",
    "numeric": "533",
    "name": "Aruban Florin",
    "symbol": "ƒ",
    "minorUnits": 2,
    "countries": [
      "AW"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "AZN",
    "numeric": "944",
    "name": "Azerbaijan Manat",
    "symbol": "₼",
    "minorUnits": 2,
    "countries": [
      "AZ"
    ],
    "aliases": [
      "manat",
      "azerbaijani manat"
    ],
    "crypto": false
  },
  {
    "code": "BAM",
    "numeric": "977",
    "name": "Convertible Mark",
    "symbol": "KM",
    "minorUnits": 2,
    "countries": [
      "BA"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BBD",
    "numeric": "052",
    "name": "Barbados Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "BB"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BDT",
    "numeric": "050",
    "name": "Taka",
    "symbol": "৳",
    "minorUnits": 2,
    "countries": [
      "BD"
    ],
    "aliases": [
      "taka",
      "bangladeshi taka"
    ],
    "crypto": false
  },
  {
    "code": "BGN",
    "numeric": "975",
    "name": "Bulgarian Lev",
    "symbol": "лв",
    "minorUnits": 2,
    "countries": [
      "BG"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BHD",
    "numeric": "048",
    "name": "Bahraini Dinar",
    "symbol": ".د.ب",
    "minorUnits": 3,
    "countries": [
      "BH"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BIF",
    "numeric": "108",
    "name": "Burundi Franc",
    "symbol": "FBu",
    "minorUnits": 0,
    "countries": [
      "BI"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BMD",
    "numeric": "060",
    "name": "Bermudian Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "BM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BND",
    "numeric": "096",
    "name": "Brunei Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "BN"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BOB",
    "numeric": "068",
    "name": "Boliviano",
    "symbol": "$b",
    "minorUnits": 2,
    "countries": [
      "BO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BOV",
    "numeric": "984",
    "name": "Mvdol",
    "symbol": "BOV",
    "minorUnits": 2,
    "countries": [
      "BO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BRL",
    "numeric": "986",
    "name": "Brazilian Real",
    "symbol": "R$",
    "minorUnits": 2,
    "countries": [
      "BR"
    ],
    "aliases": [
      "real",
      "brazilian real"
    ],
    "crypto": false
  },
  {
    "code": "BSD",
    "numeric": "044",
    "name": "Bahamian Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "BS"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BTN",
    "numeric": "064",
    "name": "Ngultrum",
    "symbol": "Nu.",
    "minorUnits": 2,
    "countries": [
      "BT"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BWP",
    "numeric": "072",
    "name": "Pula",
    "symbol": "P",
    "minorUnits": 2,
    "countries": [
      "BW"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BYN",
    "numeric": "933",
    "name": "Belarusian Ruble",
    "symbol": "Br",
    "minorUnits": 2,
    "countries": [
      "BY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BZD",
    "numeric": "084",
    "name": "Belize Dollar",
    "symbol": "BZ$",
    "minorUnits": 2,
    "countries": [
      "BZ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CAD",
    "numeric": "124",
    "name": "Canadian Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "CA"
    ],
    "aliases": [
      "canadian dollar",
      "loonie"
    ],
    "crypto": false
  },
  {
    "code": "CDF",
    "numeric": "976",
    "name": "Congolese Franc",
    "symbol": "FC",
    "minorUnits": 2,
    "countries": [
      "CD"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CHE",
    "numeric": "947",
    "name": "WIR Euro",
    "symbol": "CHE",
    "minorUnits": 2,
    "countries": [
      "CH"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CHF",
    "numeric": "756",
    "name": "Swiss Franc",
    "symbol": "CHF",
    "minorUnits": 2,
    "countries": [
      "LI",
      "CH"
    ],
    "aliases": [
      "swiss franc",
      "franc"
    ],
    "crypto": false
  },
  {
    "code": "CHW",
    "numeric": "948",
    "name": "WIR Franc",
    "symbol": "CHW",
    "minorUnits": 2,
    "countries": [
      "CH"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CLF",
    "numeric": "990",
    "name": "Unidad de Fomento",
    "symbol": "CLF",
    "minorUnits": 4,
    "countries": [
      "CL"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CLP",
    "numeric": "152",
    "name": "Chilean Peso",
    "symbol": "$",
    "minorUnits": 0,
    "countries": [
      "CL"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CNY",
    "numeric": "156",
    "name": "Yuan Renminbi",
    "symbol": "¥",
    "minorUnits": 2,
    "countries": [
      "CN"
    ],
    "aliases": [
      "yuan",
      "renminbi",
      "rmb",
      "chinese yuan"
    ],
    "crypto": false
  },
  {
    "code": "COP",
    "numeric": "170",
    "name": "Colombian Peso",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "CO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "COU",
    "numeric": "970",
    "name": "Unidad de Valor Real",
    "symbol": "COU",
    "minorUnits": 2,
    "countries": [
      "CO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CRC",
    "numeric": "188",
    "name": "Costa Rican Colon",
    "symbol": "₡",
    "minorUnits": 2,
    "countries": [
      "CR"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CUC",
    "numeric": "931",
    "name": "Peso Convertible",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "CU"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CUP",
    "numeric": "192",
    "name": "Cuban Peso",
    "symbol": "₱",
    "minorUnits": 2,
    "countries": [
      "CU"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CVE",
    "numeric": "132",
    "name": "Cabo Verde Escudo",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "CV"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "CZK",
    "numeric": "203",
    "name": "Czech Koruna",
    "symbol": "Kč",
    "minorUnits": 2,
    "countries": [
      "CZ"
    ],
    "aliases": [
      "czech koruna",
      "koruna"
    ],
    "crypto": false
  },
  {
    "code": "DJF",
    "numeric": "262",
    "name": "Djibouti Franc",
    "symbol": "Fdj",
    "minorUnits": 0,
    "countries": [
      "DJ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "DKK",
    "numeric": "208",
    "name": "Danish Krone",
    "symbol": "kr",
    "minorUnits": 2,
    "countries": [
      "DK",
      "FO",
      "GL"
    ],
    "aliases": [
      "danish krone"
    ],
    "crypto": false
  },
  {
    "code": "DOP",
    "numeric": "214",
    "name": "Dominican Peso",
    "symbol": "RD$",
    "minorUnits": 2,
    "countries": [
      "DO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "DZD",
    "numeric": "012",
    "name": "Algerian Dinar",
    "symbol": "دج",
    "minorUnits": 2,
    "countries": [
      "DZ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "EGP",
    "numeric": "818",
    "name": "Egyptian Pound",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "EG"
    ],
    "aliases": [
      "egyptian pound"
    ],
    "crypto": false
  },
  {
    "code": "ERN",
    "numeric": "232",
    "name": "Nakfa",
    "symbol": "Nfk",
    "minorUnits": 2,
    "countries": [
      "ER"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "ETB",
    "numeric": "230",
    "name": "Ethiopian Birr",
    "symbol": "Br",
    "minorUnits": 2,
    "countries": [
      "ET"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "EUR",
    "numeric": "978",
    "name": "Euro",
    "symbol": "€",
    "minorUnits": 2,
    "countries": [
      "AX",
      "AD",
      "AT",
      "BE",
      "HR",
      "CY",
      "EE",
      "FI",
      "FR",
      "GF",
      "TF",
      "DE",
      "GR",
      "GP",
      "VA",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "MQ",
      "YT",
      "MC",
      "ME",
      "NL",
      "PT",
      "RE",
      "BL",
      "MF",
      "PM",
      "SM",
      "SK",
      "SI",
      "ES"
    ],
    "aliases": [
      "euro",
      "euros"
    ],
    "crypto": false
  },
  {
    "code": "FJD",
    "numeric": "242",
    "name": "Fiji Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "FJ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "FKP",
    "numeric": "238",
    "name": "Falkland Islands Pound",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "FK"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "GBP",
    "numeric": "826",
    "name": "Pound Sterling",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "GG",
      "IM",
      "JE",
      "GB"
    ],
    "aliases": [
      "pound",
      "pound sterling",
      "sterling",
      "quid",
      "british pound"
    ],
    "crypto": false
  },
  {
    "code": "GEL",
    "numeric": "981",
    "name": "Lari",
    "symbol": "₾",
    "minorUnits": 2,
    "countries": [
      "GE"
    ],
    "aliases": [
      "lari",
      "georgian lari"
    ],
    "crypto": false
  },
  {
    "code": "GHS",
    "numeric": "936",
    "name": "Ghana Cedi",
    "symbol": "GH₵",
    "minorUnits": 2,
    "countries": [
      "GH"
    ],
    "aliases": [
      "cedi",
      "ghanaian cedi"
    ],
    "crypto": false
  },
  {
    "code": "GIP",
    "numeric": "292",
    "name": "Gibraltar Pound",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "GI"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "GMD",
    "numeric": "270",
    "name": "Dalasi",
    "symbol": "D",
    "minorUnits": 2,
    "countries": [
      "GM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "GNF",
    "numeric": "324",
    "name": "Guinean Franc",
    "symbol": "FG",
    "minorUnits": 0,
    "countries": [
      "GN"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "GTQ",
    "numeric": "320",
    "name": "Quetzal",
    "symbol": "Q",
    "minorUnits": 2,
    "countries": [
      "GT"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "GYD",
    "numeric": "328",
    "name": "Guyana Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "GY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "HKD",
    "numeric": "344",
    "name": "Hong Kong Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "HK"
    ],
    "aliases": [
      "hong kong dollar"
    ],
    "crypto": false
  },
  {
    "code": "HNL",
    "numeric": "340",
    "name": "Lempira",
    "symbol": "L",
    "minorUnits": 2,
    "countries": [
      "HN"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "HTG",
    "numeric": "332",
    "name": "Gourde",
    "symbol": "G",
    "minorUnits": 2,
    "countries": [
      "HT"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "HUF",
    "numeric": "348",
    "name": "Forint",
    "symbol": "Ft",
    "minorUnits": 2,
    "countries": [
      "HU"
    ],
    "aliases": [
      "forint",
      "hungarian forint"
    ],
    "crypto": false
  },
  {
    "code": "IDR",
    "numeric": "360",
    "name": "Rupiah",
    "symbol": "Rp",
    "minorUnits": 2,
    "countries": [
      "ID"
    ],
    "aliases": [
      "rupiah",
      "indonesian rupiah"
    ],
    "crypto": false
  },
  {
    "code": "ILS",
    "numeric": "376",
    "name": "New Israeli Sheqel",
    "symbol": "₪",
    "minorUnits": 2,
    "countries": [
      "IL"
    ],
    "aliases": [
      "shekel",
      "israeli shekel",
      "new shekel"
    ],
    "crypto": false
  },
  {
    "code": "INR",
    "numeric": "356",
    "name": "Indian Rupee",
    "symbol": "₹",
    "minorUnits": 2,
    "countries": [
      "BT",
      "IN"
    ],
    "aliases": [
      "rupee",
      "indian rupee",
      "rs"
    ],
    "crypto": false
  },
  {
    "code": "IQD",
    "numeric": "368",
    "name": "Iraqi Dinar",
    "symbol": "ع.د",
    "minorUnits": 3,
    "countries": [
      "IQ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "IRR",
    "numeric": "364",
    "name": "Iranian Rial",
    "symbol": "﷼",
    "minorUnits": 2,
    "countries": [
      "IR"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "ISK",
    "numeric": "352",
    "name": "Iceland Krona",
    "symbol": "kr",
    "minorUnits": 0,
    "countries": [
      "IS"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "JMD",
    "numeric": "388",
    "name": "Jamaican Dollar",
    "symbol": "J$",
    "minorUnits": 2,
    "countries": [
      "JM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "JOD",
    "numeric": "400",
    "name": "Jordanian Dinar",
    "symbol": "JD",
    "minorUnits": 3,
    "countries": [
      "JO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "JPY",
    "numeric": "392",
    "name": "Yen",
    "symbol": "¥",
    "minorUnits": 0,
    "countries": [
      "JP"
    ],
    "aliases": [
      "yen",
      "japanese yen"
    ],
    "crypto": false
  },
  {
    "code": "KES",
    "numeric": "404",
    "name": "Kenyan Shilling",
    "symbol": "KSh",
    "minorUnits": 2,
    "countries": [
      "KE"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "KGS",
    "numeric": "417",
    "name": "Som",
    "symbol": "лв",
    "minorUnits": 2,
    "countries": [
      "KG"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "KHR",
    "numeric": "116",
    "name": "Riel",
    "symbol": "៛",
    "minorUnits": 2,
    "countries": [
      "KH"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "KMF",
    "numeric": "174",
    "name": "Comorian Franc ",
    "symbol": "CF",
    "minorUnits": 0,
    "countries": [
      "KM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "KPW",
    "numeric": "408",
    "name": "North Korean Won",
    "symbol": "₩",
    "minorUnits": 2,
    "countries": [
      "KP"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "KRW",
    "numeric": "410",
    "name": "Won",
    "symbol": "₩",
    "minorUnits": 0,
    "countries": [
      "KR"
    ],
    "aliases": [
      "won",
      "korean won",
      "south korean won"
    ],
    "crypto": false
  },
  {
    "code": "KWD",
    "numeric": "414",
    "name": "Kuwaiti Dinar",
    "symbol": "KD",
    "minorUnits": 3,
    "countries": [
      "KW"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "KYD",
    "numeric": "136",
    "name": "Cayman Islands Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "KY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "KZT",
    "numeric": "398",
    "name": "Tenge",
    "symbol": "₸",
    "minorUnits": 2,
    "countries": [
      "KZ"
    ],
    "aliases": [
      "tenge",
      "kazakhstani tenge"
    ],
    "crypto": false
  },
  {
    "code": "LAK",
    "numeric": "418",
    "name": "Lao Kip",
    "symbol": "₭",
    "minorUnits": 2,
    "countries": [
      "LA"
    ],
    "aliases": [
      "kip",
      "lao kip"
    ],
    "crypto": false
  },
  {
    "code": "LBP",
    "numeric": "422",
    "name": "Lebanese Pound",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "LB"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "LKR",
    "numeric": "144",
    "name": "Sri Lanka Rupee",
    "symbol": "₨",
    "minorUnits": 2,
    "countries": [
      "LK"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "LRD",
    "numeric": "430",
    "name": "Liberian Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "LR"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "LSL",
    "numeric": "426",
    "name": "Loti",
    "symbol": "M",
    "minorUnits": 2,
    "countries": [
      "LS"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "LYD",
    "numeric": "434",
    "name": "Libyan Dinar",
    "symbol": "LD",
    "minorUnits": 3,
    "countries": [
      "LY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MAD",
    "numeric": "504",
    "name": "Moroccan Dirham",
    "symbol": "MAD",
    "minorUnits": 2,
    "countries": [
      "MA",
      "EH"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MDL",
    "numeric": "498",
    "name": "Moldovan Leu",
    "symbol": "lei",
    "minorUnits": 2,
    "countries": [
      "MD"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MGA",
    "numeric": "969",
    "name": "Malagasy Ariary",
    "symbol": "Ar",
    "minorUnits": 2,
    "countries": [
      "MG"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MKD",
    "numeric": "807",
    "name": "Denar",
    "symbol": "ден",
    "minorUnits": 2,
    "countries": [
      "MK"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MMK",
    "numeric": "104",
    "name": "Kyat",
    "symbol": "K",
    "minorUnits": 2,
    "countries": [
      "MM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MNT",
    "numeric": "496",
    "name": "Tugrik",
    "symbol": "₮",
    "minorUnits": 2,
    "countries": [
      "MN"
    ],
    "aliases": [
      "tugrik",
      "mongolian tugrik"
    ],
    "crypto": false
  },
  {
    "code": "MOP",
    "numeric": "446",
    "name": "Pataca",
    "symbol": "MOP$",
    "minorUnits": 2,
    "countries": [
      "MO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MRU",
    "numeric": "929",
    "name": "Ouguiya",
    "symbol": "UM",
    "minorUnits": 2,
    "countries": [
      "MR"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MUR",
    "numeric": "480",
    "name": "Mauritius Rupee",
    "symbol": "₨",
    "minorUnits": 2,
    "countries": [
      "MU"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MVR",
    "numeric": "462",
    "name": "Rufiyaa",
    "symbol": "Rf",
    "minorUnits": 2,
    "countries": [
      "MV"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MWK",
    "numeric": "454",
    "name": "Malawi Kwacha",
    "symbol": "MK",
    "minorUnits": 2,
    "countries": [
      "MW"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MXN",
    "numeric": "484",
    "name": "Mexican Peso",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "MX"
    ],
    "aliases": [
      "mexican peso",
      "peso"
    ],
    "crypto": false
  },
  {
    "code": "MXV",
    "numeric": "979",
    "name": "Mexican Unidad de Inversion (UDI)",
    "symbol": "MXV",
    "minorUnits": 2,
    "countries": [
      "MX"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "MYR",
    "numeric": "458",
    "name": "Malaysian Ringgit",
    "symbol": "RM",
    "minorUnits": 2,
    "countries": [
      "MY"
    ],
    "aliases": [
      "ringgit",
      "malaysian ringgit"
    ],
    "crypto": false
  },
  {
    "code": "MZN",
    "numeric": "943",
    "name": "Mozambique Metical",
    "symbol": "MT",
    "minorUnits": 2,
    "countries": [
      "MZ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "NAD",
    "numeric": "516",
    "name": "Namibia Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "NA"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "NGN",
    "numeric": "566",
    "name": "Naira",
    "symbol": "₦",
    "minorUnits": 2,
    "countries": [
      "NG"
    ],
    "aliases": [
      "naira",
      "nigerian naira"
    ],
    "crypto": false
  },
  {
    "code": "NIO",
    "numeric": "558",
    "name": "Cordoba Oro",
    "symbol": "C$",
    "minorUnits": 2,
    "countries": [
      "NI"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "NOK",
    "numeric": "578",
    "name": "Norwegian Krone",
    "symbol": "kr",
    "minorUnits": 2,
    "countries": [
      "BV",
      "NO",
      "SJ"
    ],
    "aliases": [
      "norwegian krone"
    ],
    "crypto": false
  },
  {
    "code": "NPR",
    "numeric": "524",
    "name": "Nepalese Rupee",
    "symbol": "₨",
    "minorUnits": 2,
    "countries": [
      "NP"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "NZD",
    "numeric": "554",
    "name": "New Zealand Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "CK",
      "NZ",
      "NU",
      "PN",
      "TK"
    ],
    "aliases": [
      "new zealand dollar",
      "kiwi dollar"
    ],
    "crypto": false
  },
  {
    "code": "OMR",
    "numeric": "512",
    "name": "Rial Omani",
    "symbol": "﷼",
    "minorUnits": 3,
    "countries": [
      "OM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "PAB",
    "numeric": "590",
    "name": "Balboa",
    "symbol": "B/.",
    "minorUnits": 2,
    "countries": [
      "PA"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "PEN",
    "numeric": "604",
    "name": "Sol",
    "symbol": "S/.",
    "minorUnits": 2,
    "countries": [
      "PE"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "PGK",
    "numeric": "598",
    "name": "Kina",
    "symbol": "K",
    "minorUnits": 2,
    "countries": [
      "PG"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "PHP",
    "numeric": "608",
    "name": "Philippine Peso",
    "symbol": "₱",
    "minorUnits": 2,
    "countries": [
      "PH"
    ],
    "aliases": [
      "philippine peso"
    ],
    "crypto": false
  },
  {
    "code": "PKR",
    "numeric": "586",
    "name": "Pakistan Rupee",
    "symbol": "₨",
    "minorUnits": 2,
    "countries": [
      "PK"
    ],
    "aliases": [
      "pakistani rupee"
    ],
    "crypto": false
  },
  {
    "code": "PLN",
    "numeric": "985",
    "name": "Zloty",
    "symbol": "zł",
    "minorUnits": 2,
    "countries": [
      "PL"
    ],
    "aliases": [
      "zloty",
      "polish zloty"
    ],
    "crypto": false
  },
  {
    "code": "PYG",
    "numeric": "600",
    "name": "Guarani",
    "symbol": "Gs",
    "minorUnits": 0,
    "countries": [
      "PY"
    ],
    "aliases": [
      "guarani",
      "paraguayan guarani"
    ],
    "crypto": false
  },
  {
    "code": "QAR",
    "numeric": "634",
    "name": "Qatari Rial",
    "symbol": "﷼",
    "minorUnits": 2,
    "countries": [
      "QA"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "RON",
    "numeric": "946",
    "name": "Romanian Leu",
    "symbol": "lei",
    "minorUnits": 2,
    "countries": [
      "RO"
    ],
    "aliases": [
      "leu",
      "romanian leu"
    ],
    "crypto": false
  },
  {
    "code": "RSD",
    "numeric": "941",
    "name": "Serbian Dinar",
    "symbol": "Дин.",
    "minorUnits": 2,
    "countries": [
      "RS"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "RUB",
    "numeric": "643",
    "name": "Russian Ruble",
    "symbol": "₽",
    "minorUnits": 2,
    "countries": [
      "RU"
    ],
    "aliases": [
      "ruble",
      "rouble",
      "russian ruble"
    ],
    "crypto": false
  },
  {
    "code": "RWF",
    "numeric": "646",
    "name": "Rwanda Franc",
    "symbol": "R₣",
    "minorUnits": 0,
    "countries": [
      "RW"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SAR",
    "numeric": "682",
    "name": "Saudi Riyal",
    "symbol": "﷼",
    "minorUnits": 2,
    "countries": [
      "SA"
    ],
    "aliases": [
      "riyal",
      "saudi riyal"
    ],
    "crypto": false
  },
  {
    "code": "SBD",
    "numeric": "090",
    "name": "Solomon Islands Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "SB"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SCR",
    "numeric": "690",
    "name": "Seychelles Rupee",
    "symbol": "₨",
    "minorUnits": 2,
    "countries": [
      "SC"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SDG",
    "numeric": "938",
    "name": "Sudanese Pound",
    "symbol": "ج.س.",
    "minorUnits": 2,
    "countries": [
      "SD"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SEK",
    "numeric": "752",
    "name": "Swedish Krona",
    "symbol": "kr",
    "minorUnits": 2,
    "countries": [
      "SE"
    ],
    "aliases": [
      "swedish krona",
      "krona"
    ],
    "crypto": false
  },
  {
    "code": "SGD",
    "numeric": "702",
    "name": "Singapore Dollar",
    "symbol": "S$",
    "minorUnits": 2,
    "countries": [
      "SG"
    ],
    "aliases": [
      "singapore dollar"
    ],
    "crypto": false
  },
  {
    "code": "SHP",
    "numeric": "654",
    "name": "Saint Helena Pound",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "SH"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SLE",
    "numeric": "925",
    "name": "Leone",
    "symbol": "SLE",
    "minorUnits": 2,
    "countries": [
      "SL"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SOS",
    "numeric": "706",
    "name": "Somali Shilling",
    "symbol": "S",
    "minorUnits": 2,
    "countries": [
      "SO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SRD",
    "numeric": "968",
    "name": "Surinam Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "SR"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SSP",
    "numeric": "728",
    "name": "South Sudanese Pound",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "SS"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "STN",
    "numeric": "930",
    "name": "Dobra",
    "symbol": "Db",
    "minorUnits": 2,
    "countries": [
      "ST"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SVC",
    "numeric": "222",
    "name": "El Salvador Colon",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "SV"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SYP",
    "numeric": "760",
    "name": "Syrian Pound",
    "symbol": "£",
    "minorUnits": 2,
    "countries": [
      "SY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "SZL",
    "numeric": "748",
    "name": "Lilangeni",
    "symbol": "E",
    "minorUnits": 2,
    "countries": [
      "SZ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "THB",
    "numeric": "764",
    "name": "Baht",
    "symbol": "฿",
    "minorUnits": 2,
    "countries": [
      "TH"
    ],
    "aliases": [
      "baht",
      "thai baht"
    ],
    "crypto": false
  },
  {
    "code": "TJS",
    "numeric": "972",
    "name": "Somoni",
    "symbol": "SM",
    "minorUnits": 2,
    "countries": [
      "TJ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "TMT",
    "numeric": "934",
    "name": "Turkmenistan New Manat",
    "symbol": "T",
    "minorUnits": 2,
    "countries": [
      "TM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "TND",
    "numeric": "788",
    "name": "Tunisian Dinar",
    "symbol": "د.ت",
    "minorUnits": 3,
    "countries": [
      "TN"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "TOP",
    "numeric": "776",
    "name": "Pa’anga",
    "symbol": "T$",
    "minorUnits": 2,
    "countries": [
      "TO"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "TRY",
    "numeric": "949",
    "name": "Turkish Lira",
    "symbol": "₺",
    "minorUnits": 2,
    "countries": [
      "TR"
    ],
    "aliases": [
      "turkish lira",
      "lira"
    ],
    "crypto": false
  },
  {
    "code": "TTD",
    "numeric": "780",
    "name": "Trinidad and Tobago Dollar",
    "symbol": "TT$",
    "minorUnits": 2,
    "countries": [
      "TT"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "TWD",
    "numeric": "901",
    "name": "New Taiwan Dollar",
    "symbol": "NT$",
    "minorUnits": 2,
    "countries": [
      "TW"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "TZS",
    "numeric": "834",
    "name": "Tanzanian Shilling",
    "symbol": "TSh",
    "minorUnits": 2,
    "countries": [
      "TZ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "UAH",
    "numeric": "980",
    "name": "Hryvnia",
    "symbol": "₴",
    "minorUnits": 2,
    "countries": [
      "UA"
    ],
    "aliases": [
      "hryvnia",
      "ukrainian hryvnia"
    ],
    "crypto": false
  },
  {
    "code": "UGX",
    "numeric": "800",
    "name": "Uganda Shilling",
    "symbol": "USh",
    "minorUnits": 0,
    "countries": [
      "UG"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "USD",
    "numeric": "840",
    "name": "US Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "AS",
      "BQ",
      "IO",
      "EC",
      "SV",
      "GU",
      "HT",
      "MH",
      "FM",
      "MP",
      "PW",
      "PA",
      "PR",
      "TL",
      "TC",
      "UM",
      "US",
      "VG",
      "VI"
    ],
    "aliases": [
      "us dollar",
      "american dollar",
      "buck",
      "bucks",
      "greenback"
    ],
    "crypto": false
  },
  {
    "code": "USN",
    "numeric": "997",
    "name": "US Dollar (Next day)",
    "symbol": "USN",
    "minorUnits": 2,
    "countries": [
      "US"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "UYI",
    "numeric": "940",
    "name": "Uruguay Peso en Unidades Indexadas (UI)",
    "symbol": "UYI",
    "minorUnits": 0,
    "countries": [
      "UY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "UYU",
    "numeric": "858",
    "name": "Peso Uruguayo",
    "symbol": "$U",
    "minorUnits": 2,
    "countries": [
      "UY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "UYW",
    "numeric": "927",
    "name": "Unidad Previsional",
    "symbol": "UYW",
    "minorUnits": 4,
    "countries": [
      "UY"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "UZS",
    "numeric": "860",
    "name": "Uzbekistan Sum",
    "symbol": "лв",
    "minorUnits": 2,
    "countries": [
      "UZ"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "VED",
    "numeric": "926",
    "name": "Bolívar Soberano",
    "symbol": "VED",
    "minorUnits": 2,
    "countries": [
      "VE"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "VES",
    "numeric": "928",
    "name": "Bolívar Soberano",
    "symbol": "Bs.S",
    "minorUnits": 2,
    "countries": [
      "VE"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "VND",
    "numeric": "704",
    "name": "Dong",
    "symbol": "₫",
    "minorUnits": 0,
    "countries": [
      "VN"
    ],
    "aliases": [
      "dong",
      "vietnamese dong"
    ],
    "crypto": false
  },
  {
    "code": "VUV",
    "numeric": "548",
    "name": "Vatu",
    "symbol": "VT",
    "minorUnits": 0,
    "countries": [
      "VU"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "WST",
    "numeric": "882",
    "name": "Tala",
    "symbol": "WS$",
    "minorUnits": 2,
    "countries": [
      "WS"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XAF",
    "numeric": "950",
    "name": "CFA Franc BEAC",
    "symbol": "FCFA",
    "minorUnits": 0,
    "countries": [
      "CM",
      "CF",
      "TD",
      "CG",
      "GQ",
      "GA"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XAG",
    "numeric": "961",
    "name": "Silver",
    "symbol": "XAG",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XAU",
    "numeric": "959",
    "name": "Gold",
    "symbol": "XAU",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XBA",
    "numeric": "955",
    "name": "Bond Markets Unit European Composite Unit (EURCO)",
    "symbol": "XBA",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XBB",
    "numeric": "956",
    "name": "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
    "symbol": "XBB",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XBC",
    "numeric": "957",
    "name": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
    "symbol": "XBC",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XBD",
    "numeric": "958",
    "name": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
    "symbol": "XBD",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XCD",
    "numeric": "951",
    "name": "East Caribbean Dollar",
    "symbol": "$",
    "minorUnits": 2,
    "countries": [
      "AI",
      "AG",
      "DM",
      "GD",
      "MS",
      "KN",
      "LC",
      "VC"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XDR",
    "numeric": "960",
    "name": "SDR (Special Drawing Right)",
    "symbol": "XDR",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XOF",
    "numeric": "952",
    "name": "CFA Franc BCEAO",
    "symbol": "CFA",
    "minorUnits": 0,
    "countries": [
      "BJ",
      "BF",
      "CI",
      "GW",
      "ML",
      "NE",
      "SN",
      "TG"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XPD",
    "numeric": "964",
    "name": "Palladium",
    "symbol": "XPD",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XPF",
    "numeric": "953",
    "name": "CFP Franc",
    "symbol": "₣",
    "minorUnits": 0,
    "countries": [
      "PF",
      "NC",
      "WF"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XPT",
    "numeric": "962",
    "name": "Platinum",
    "symbol": "XPT",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XSU",
    "numeric": "994",
    "name": "Sucre",
    "symbol": "Sucre",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XTS",
    "numeric": "963",
    "name": "Codes specifically reserved for testing purposes",
    "symbol": "XTS",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XUA",
    "numeric": "965",
    "name": "ADB Unit of Account",
    "symbol": "XUA",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "XXX",
    "numeric": "999",
    "name": "The codes assigned for transactions where no currency is involved",
    "symbol": "XXX",
    "minorUnits": 0,
    "countries": [],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "YER",
    "numeric": "886",
    "name": "Yemeni Rial",
    "symbol": "﷼",
    "minorUnits": 2,
    "countries": [
      "YE"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "ZAR",
    "numeric": "710",
    "name": "Rand",
    "symbol": "R",
    "minorUnits": 2,
    "countries": [
      "LS",
      "NA",
      "ZA"
    ],
    "aliases": [
      "rand",
      "south african rand"
    ],
    "crypto": false
  },
  {
    "code": "ZMW",
    "numeric": "967",
    "name": "Zambian Kwacha",
    "symbol": "ZK",
    "minorUnits": 2,
    "countries": [
      "ZM"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "ZWG",
    "numeric": "924",
    "name": "Zimbabwe Gold",
    "symbol": "ZWG",
    "minorUnits": 2,
    "countries": [
      "ZW"
    ],
    "aliases": [],
    "crypto": false
  },
  {
    "code": "BTC",
    "numeric": "",
    "name": "Bitcoin",
    "symbol": "₿",
    "minorUnits": 8,
    "countries": [],
    "aliases": [
      "bitcoin",
      "btc",
      "xbt"
    ],
    "crypto": true
  },
  {
    "code": "ETH",
    "numeric": "",
    "name": "Ethereum",
    "symbol": "Ξ",
    "minorUnits": 18,
    "countries": [],
    "aliases": [
      "ethereum",
      "eth",
      "ether"
    ],
    "crypto": true
  },
  {
    "code": "LTC",
    "numeric": "",
    "name": "Litecoin",
    "symbol": "Ł",
    "minorUnits": 8,
    "countries": [],
    "aliases": [
      "litecoin",
      "ltc"
    ],
    "crypto": true
  },
  {
    "code": "XRP",
    "numeric": "",
    "name": "Ripple",
    "symbol": "✕",
    "minorUnits": 6,
    "countries": [],
    "aliases": [
      "ripple",
      "xrp"
    ],
    "crypto": true
  },
  {
    "code": "XMR",
    "numeric": "",
    "name": "Monero",
    "symbol": "ɱ",
    "minorUnits": 12,
    "countries": [],
    "aliases": [
      "monero",
      "xmr"
    ],
    "crypto": true
  }
] as const;
